#!/usr/bin/bash

get_package_manager() {
  declare -A osInfo;
  osInfo[/etc/redhat-release]=dnf
  osInfo[/etc/arch-release]=pacman
  osInfo[/etc/gentoo-release]=emerge
  osInfo[/etc/SuSE-release]=zypp
  osInfo[/etc/debian_version]=apt-get
  osInfo[/etc/alpine-release]=apk

for f in ${!osInfo[@]}
do
    if [[ -f $f ]];then
      echo ${osInfo[$f]}
    fi
done
}


echo -e "-----------------------Voms Setup--------------------------"
echo -e "\n--> System Configuration:"
cat /etc/os-release || cat /etc/lsb-release
echo -e "\n--> Proceeding with Package Manager:"
pm=$(get_package_manager)
echo "$pm"
echo -e "\n--> Installing voms ..."
sudo $pm install voms-clients-cpp
echo -e "\n--> Copying the necessary CA certificates"
sudo mkdir -p /etc/grid-security/certificates/
sudo unzip -o assets/certs.zip -d /etc/grid-security/certificates/
echo -e "\n--> Copying the CMS vomses"
sudo mkdir -p /etc/grid-security/vomsdir/
sudo cp -r assets/cms/ /etc/grid-security/vomsdir/
echo -e "\n--> Copying the gsi configuration"
sudo cp assets/gsi.conf /etc/grid-security/
echo "-----------------------Setup Complete--------------------------"
